repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev:  v1.50.0
    hooks:
      # - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: checkov
      - id: terrascan
      - id: terraform_docs
      - id: terragrunt_validate
      - id: terragrunt_fmt
  - repo: local
    hooks:
      - id: terraform_fmt
        name: terraform_fmt
        entry: bash -c 'terraform fmt -recursive'
        language: system